### ISSUE TITLE
Non valid startup probe example

### ISSUE THREAD

**Issue by RubenMakandra** [book-of-kubernetes/examples#21]
In Chapter 13 of the book, section Startup Probes, is an example for a Startup Probe definition:

```
...
        startupProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 60
```
The key periodSeconds is given twice, once with an empty value, and then with 10, instead of being unique as required by the specification.
